### ISSUE TITLE
Add capability of systematic sample design for subplots

### ISSUE THREAD

**Issue by pmaus** [sig-gis/mapcha#11]
Allow user to choose the distribution of the "samples per plot" option for systematic, random, or both systematic and random (user chooses how many systematic plots versus number of random plots). This is so we can get a better distribution of samples without increasing the number of samples.

**Comment by lambdatronic** [comment]
The Admin page now supports both random and gridded sample distributions during new project creation. Currently we only allow one or the other sample design to be chosen.
