### ISSUE TITLE
Add "sample frame" options (configuration, size)

### ISSUE THREAD

**Issue by petecutter** [sig-gis/mapcha#19]
It would be nice to have a 'mode' that emulates the widely-used Collect Earth plot configuration and collection format...so that samples could be consistent between the two platforms. Another important variable/option is plot size...that should be flexible to serve the needs of different sampling efforts.

**Comment by lambdatronic** [comment]
Plot size can be set when creating a new project in the Admin page. Samples may now be specified with either a Random or Gridded distribution for Collect Earth compatibility.
