### ISSUE TITLE
admin project page legend box

### ISSUE THREAD

**Issue by andersoner** [sig-gis/mapcha#3]
legend box bleeds over bottom of page

**Comment by lambdatronic** [comment]
Good eye, Eric. The Dashboard sidebar is dynamically sized according to its contents, but the page background and footer were not being updated accordingly. The same thing happens on the Admin page if you add enough Sample Values to the table. I fixed this on the Dashboard today, and I'll get to the Admin page shortly.

**Comment by lambdatronic** [comment]
Okay, I've fixed the Admin page as well. We should all be set now.
