### ISSUE TITLE
what do we do about inadequate basemaps?

### ISSUE THREAD

**Issue by andersoner** [sig-gis/mapcha#4]
some plots show up with a black background if there isn't adequate basemap imagery:

![screen shot 2016-07-12 at 11 31 33 am](https://cloud.githubusercontent.com/assets/8808272/16755261/cba15dfe-4824-11e6-9d0b-07383e685201.png)

zooming out allows the basemap to eventually show up, but it is sometimes too coarse to allow for a reasonable analysis:

![screen shot 2016-07-12 at 11 31 50 am](https://cloud.githubusercontent.com/assets/8808272/16755263/ce68593e-4824-11e6-8cad-c2fb152f2344.png)

is there a way to not allow plots to be designated over places with inadequate basemap imagery? or do we deal with this another way?

**Comment by lambdatronic** [comment]
Hi Eric,

I just resolved this when I closed issue #5. Please see my comments on that thread for details on how the new plot flagging feature works.
