### ISSUE TITLE
Add "go to new plot" button when no cloud-free imagery is available

### ISSUE THREAD

**Issue by pmaus** [sig-gis/mapcha#5]
When a new plot lands in an area where there is no imagery it would be helpful to have a button to just move to next plot rather than having to select the sample and label them "unknown".

**Comment by lambdatronic** [comment]
Now when you press "Analyze New Plot", the map will zoom to a new plot and the button will change to say "Flag Plot as Bad". You may now still proceed as before with assigning colors to sample points and then press "Save Assignments" to record them in the database. However, if at any point you choose to press the "Flag Plot as Bad" button, any assignments you have made thus far will be discarded, the plot will be flagged in the database, and a new plot will automatically be loaded.

The effect of flagging a plot is that "Analyze New Plot" will never again present it to another user. Also, when exporting plot-level CSV data with the "Download Data" button on the Admin page, the flagged field is included with each plot in the output dataset.
