### ISSUE TITLE
Provide image and location metadata in dashboard

### ISSUE THREAD

**Issue by pmaus** [sig-gis/mapcha#6]
Provide year and month of imagery as well as plot center coordinate (lat/lon) somewhere on the dashboard.

**Comment by lambdatronic** [comment]
The imagery title, date (month and year), and source attribution are now displayed below the map on the Dashboard page. David Saah has requested that the plot center coordinate not be revealed to the user. Feel free to discuss this further with him and reopen this issue if necessary.

**Comment by pmaus** [comment]
Yes-I talked to Dave about that. I think the image date is helpful for the
interpreters so thanks for putting that in.

Paul
