### ISSUE TITLE
Provide polygon option for defining survey area under admin

### ISSUE THREAD

**Issue by pmaus** [sig-gis/mapcha#7]
provide a polygon tool for defining a survey area in addition to the lat/lon box.

**Comment by lambdatronic** [comment]
I added functionality to the Admin page that allows the user to draw a bounding box on the map with a ctrl-click-and-drag action. This records the lat/lon coords of the box's extent in the "Define Bounding Box" fields. The user can redraw this rectangle as many times as they like. It will just keep erasing and replacing the previous one.

Currently, the plot and sample point generation algorithms expect that a project's bounding box is a rectangle, not an arbitrary polygon. I am hoping that this UI feature will make entering them easier for the user going forward.

Does this meet your needs?
